import {IProductInfoDefaultObj} from '../constants/productInfoDefaults';

const generateConfigObj = (configData: IProductInfoDefaultObj) => ({
  PRODUCT_ID: configData.product_id,
  APP_NAME: configData.product_name || '',
  APP_ID: configData.app_id || '',
  PRIMARY_COLOR: configData.primary_color || '',
  FRONTEND_ENDPOINT: configData.frontend_endpoint || '',
  BACKEND_ENDPOINT: configData.backend_endpoint || '',
  PSTN: configData.pstn,
  PRECALL: configData.precall,
  CHAT: configData.chat,
  CLOUD_RECORDING: configData.cloud_recording,
  SCREEN_SHARING: configData.screen_sharing,
  LANDING_SUB_HEADING: configData.landing_sub_heading || '',
  ENCRYPTION_ENABLED: configData.encryption_enabled,
  PRIMARY_FONT_COLOR: configData.primary_font_color || '',
  SECONDARY_FONT_COLOR: configData.secondary_font_color || '',
  SENTRY_DSN: configData.sentry_dsn,
  ENABLE_GOOGLE_OAUTH: configData.enable_google_oauth,
  ENABLE_SLACK_OAUTH: configData.enable_slack_oauth,
  ENABLE_MICROSOFT_OAUTH: configData.enable_microsoft_oauth,
  ENABLE_APPLE_OAUTH: configData.enable_apple_oauth,
  APP_CERTIFICATE: configData.app_certificate || '',
  GOOGLE_CLIENT_ID: configData.google_client_id || '',
  GOOGLE_CLIENT_SECRET: configData.google_client_secret || '',
  MICROSOFT_CLIENT_ID: configData.microsoft_client_id || '',
  MICROSOFT_CLIENT_SECRET: configData.microsoft_client_secret || '',
  SLACK_CLIENT_ID: configData.slack_client_id || '',
  SLACK_CLIENT_SECRET: configData.slack_client_secret || '',
  APPLE_CLIENT_ID: configData.apple_client_id || '',
  APPLE_KEY_ID: configData.apple_key_id || '',
  APPLE_PRIVATE_KEY: configData.apple_private_key || '',
  APPLE_TEAM_ID: configData.apple_team_id || '',
  CUSTOMER_ID: configData.customer_id || '',
  CUSTOMER_CERTIFICATE: configData.customer_certificate || '',
  BUCKET_NAME: configData.bucket_name || '',
  RECORDING_REGION: configData.recording_region || '',
  BUCKET_ACCESS_KEY: configData.bucket_access_key || '',
  BUCKET_ACCESS_SECRET: configData.bucket_access_secret || '',
  PSTN_EMAIL: configData.pstn_email || '',
  PSTN_PASSWORD: configData.pstn_password || '',
  PSTN_ACCOUNT: configData.pstn_account || '',
  PROFILE: '480p_8',
});
export default generateConfigObj;
